### ISSUE TITLE
Double Colon in Edit-Mode

### ISSUE THREAD

**Issue by Pluralog** [msrch/obsidian-double-colon-conceal#3]
Hey Michael, great plugin. This is really what I was [waiting for](https://forum.obsidian.md/t/show-double-colon-from-dataview-as-one-when-not-editing-the-line/42656). Since I only use the new edit mode nowadays, as a feature idea, I would love to have this in edit mode too. So, that the double colon is only shown in active lines.

**Comment by msrch** [comment]
Hey thank you for your interest in this plugin. Originally when building this plugin I have disregarded this since I prefer to see the double colons in edit mode. Having said that I can see this being useful, so I have build quick proof of concept.

[double-colon-conceal-edit-mode-poc-demo.webm](https://user-images.githubusercontent.com/5042903/220326041-8cf2768b-9bdb-404b-af88-166b7d577853.webm)

Is this what you had in mind?

It will take more time (no timeline) to properly build this feature since I will put it behind toggle in plugin settings (which currency doesn't  exists, needs building) and will have to clean up and optimize most of the POC. And also testing... speaking of that would you be willing to help with that when I have a beta build ready?

**Comment by Pluralog** [comment]
Yes. That looks exactly like what I had in mind!
Unfortunately, I can't write a proper line of code. So testing is all I can do.

**Comment by msrch** [comment]
Beta version released https://github.com/msrch/obsidian-double-colon-conceal/releases/tag/1.2.0-beta.1

Easiest way to test it is to use [BRAT](https://github.com/TfTHacker/obsidian42-brat) and choose the "Add beta plugin with frozen version" - `1.2.0-beta.1` (you will have uninstall the plugin first before installing it using BRAT).

You will have to enable the "conceal in editing view" manually in the plugin settings - disabled by default.

![screenshot_20230223_205151](https://user-images.githubusercontent.com/5042903/221027653-e13c5628-53c4-4abc-95c9-b17527adcc02.png)

As mentioned in the description in settings there is `.cm-double-colon-conceal` CSS class attached to the concealed double colon in the editing view so you can style it if needed. Example below - custom red colour:

![screenshot_20230223_210356](https://user-images.githubusercontent.com/5042903/221029870-2945cd7b-5727-4329-9465-0b1bace92814.png)


So far I have tested it on Linux desktop and Android mobile and both seem to work fine.

**Comment by Pluralog** [comment]
Wow, that was quick. I love the idea of marking the concealed dataview colon with a slightly different colour.
Tested it on Obsidian for macOS and iOS with the Top5 Colour Schemes, and it works like a charm!

**Comment by msrch** [comment]
Great! Thank you very much for the help with testing. Can also confirm that it works on Windows.

New version [1.2.0](https://github.com/msrch/obsidian-double-colon-conceal/releases/tag/1.2.0) got released.
