### ISSUE TITLE
[BUG] '(', ')', '[' and ']' don't remove double colon

### ISSUE THREAD

**Issue by OmniNaut** [msrch/obsidian-double-colon-conceal#4]
Hi,

I found some other characters that don't remove double colon in reading mode.
The characters are: ( ) [ ]

Exapmple:
- Bla ():: 
Does still show double colon in reading mode

**Comment by msrch** [comment]
Thanks for reporting the issue.

Currently any `[ ] ( ) :` characters are blacklisted so this doesn't interfere with the "metadata inside sentences" fields `[key:: value]` and `(key:: value)` since they are handled/concealed by Dataview in reading mode.

I can improve the logic so it will only blacklist the cases where `[ (` is not closed so the cases like `Bla ()::` will still be considered as valid field names and thus concealed.

One of the reasons why I have excluded above mentioned characters was that they result in invalid Dataview fields in my testing.

![screenshot_20230306_104354](https://user-images.githubusercontent.com/5042903/223092218-cfaecef7-6565-443e-b111-ac2e00bd6787.png)

Out of interest @OmniNaut does fields like this work for you? Or if you can provide some examples which I can use for testing, that would be great, thanks. I am fine with fixing this for sake of visual consistency, if this is what you would like.

**Comment by OmniNaut** [comment]
Hi, 

yeah I was already thinking that these characters were used for metadata stuff.
Currently I solved the problem by using the @ symbol instead of () 
![image](https://user-images.githubusercontent.com/110312864/223620768-b07d930c-79a8-45d7-b4f9-db755a2c67f9.png)

Ecstatically I prefer to use () but the new solution also works for me. 
So for me personally it would be a nice to have.
Although I cannot speak for the other users, maybe for other users it will be more important to have () and [] accepted.

Thanks for your time and effort on this👍🏼

**Comment by msrch** [comment]
New version with the fix got released [1.2.2](https://github.com/msrch/obsidian-double-colon-conceal/releases/tag/1.2.2)

It is now allowing pretty much any character in the field name except the `::` which is used as the delimiter by Dataview. There is only one rule and that is "if one of the brackets (square or round) is left opened" this will count as invalid field name (double colon not concealed) since it will basically become the "metadata inside sentences" field like `[key:: value]` or `(key:: value)`.

Here are some examples:

![screenshot_20230308](https://user-images.githubusercontent.com/5042903/223788242-5b173f30-1dcb-4fec-b379-e4b17018181a.png)

**Comment by OmniNaut** [comment]
Seems to be working fine now.

Thanks 👍🏼
